<%@ Page Title="Admin - Books" Language="C#"
    MasterPageFile="~/Site.Master"
    AutoEventWireup="true"
    CodeBehind="Books.aspx.cs"
    Inherits="BookStoreManagementSystem.Admin.Books" %>

<asp:Content ContentPlaceHolderID="MainContent" runat="server">

<h3 class="mb-4">📚 Manage Books</h3>

<!-- ADD BOOK -->
<div class="card mb-4 shadow-sm">
    <div class="card-body">
        <h5>Add New Book</h5>

        <div class="row g-2">
            <div class="col-md-4">
                <asp:TextBox ID="txtTitle" runat="server"
                    CssClass="form-control" Placeholder="Title" />
            </div>
            <div class="col-md-3">
                <asp:TextBox ID="txtAuthor" runat="server"
                    CssClass="form-control" Placeholder="Author" />
            </div>
            <div class="col-md-2">
                <asp:TextBox ID="txtPrice" runat="server"
                    CssClass="form-control" Placeholder="Price" />
            </div>
            <div class="col-md-3">
                <asp:Button ID="btnAdd"
                    runat="server"
                    Text="Add Book"
                    CssClass="btn btn-success w-100"
                    OnClick="btnAdd_Click" />
            </div>
        </div>
    </div>
</div>

<!-- BOOKS GRID -->
<asp:GridView ID="gvBooks" runat="server"
    CssClass="table table-bordered table-striped"
    AutoGenerateColumns="False"
    DataKeyNames="BookId"
    AutoGenerateEditButton="true"
    AutoGenerateDeleteButton="true"
    OnRowEditing="gvBooks_RowEditing"
    OnRowCancelingEdit="gvBooks_RowCancelingEdit"
    OnRowUpdating="gvBooks_RowUpdating"
    OnRowDeleting="gvBooks_RowDeleting">

    <Columns>
        <asp:BoundField DataField="Title" HeaderText="Title" />
        <asp:BoundField DataField="Author" HeaderText="Author" />
        <asp:BoundField DataField="Price" HeaderText="Price" />
    </Columns>

</asp:GridView>

</asp:Content>
